// GENERATED by scripts/generate_mission_params_rules.py — do not edit.
// SSOT: schemas/common/mission_params_rules.1.1.json
#pragma once

#include <cstddef>
#include <string_view>

namespace satellite {
namespace mission_params_rules {

using std::string_view_literals::operator""sv;

struct Rules {
    const std::string_view* required;
    std::size_t required_count;
    const std::string_view* forbidden;
    std::size_t forbidden_count;
};

inline constexpr std::string_view kRequired_HISTORICAL_REPLAY[] = {"receiver"sv, "time_range"sv};
inline constexpr std::string_view kForbidden_HISTORICAL_REPLAY[] = {"target_lla"sv, "execute_ip"sv};

inline constexpr std::string_view kRequired_REMOTE_DETECTION[] = {"target_lla"sv, "receiver"sv, "time_range"sv};
inline constexpr std::string_view kForbidden_REMOTE_DETECTION[] = {"execute_ip"sv};

inline constexpr std::string_view kRequired_SINGLE_REMOTE_DETECTION[] = {"target_lla"sv, "receiver"sv, "time_range"sv, "execute_ip"sv};

inline const Rules* find(std::string_view task_type) {
    if (task_type == "historical_replay"sv) {
        static const Rules r{
            kRequired_HISTORICAL_REPLAY, 2, kForbidden_HISTORICAL_REPLAY, 2};
        return &r;
    }
    if (task_type == "remote_detection"sv) {
        static const Rules r{
            kRequired_REMOTE_DETECTION, 3, kForbidden_REMOTE_DETECTION, 1};
        return &r;
    }
    if (task_type == "single_remote_detection"sv) {
        static const Rules r{
            kRequired_SINGLE_REMOTE_DETECTION, 4, nullptr, 0};
        return &r;
    }
    return nullptr;
}

}  // namespace mission_params_rules
}  // namespace satellite
