#!/usr/bin/env python3
"""Generate Mission params artifacts from schemas/common/mission_params_rules.1.1.json.

SSOT: mission_params_rules.1.1.json
Outputs (do not hand-edit):
  - schemas/common/mission_params_by_task_type.1.1.generated.schema.json
  - src/satellite/mission_params_rules.generated.hpp

Usage:
  python3 scripts/generate_mission_params_rules.py          # write
  python3 scripts/generate_mission_params_rules.py --check  # exit 1 if stale
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RULES_PATH = ROOT / "schemas/common/mission_params_rules.1.1.json"
SCHEMA_OUT = ROOT / "schemas/common/mission_params_by_task_type.1.1.generated.schema.json"
HPP_OUT = ROOT / "src/satellite/mission_params_rules.generated.hpp"

FIELD_SCHEMA_REF = {
    "receiver": "receiver.schema.json",
    "time_range": "time_range.schema.json",
    "target_lla": "geo_point.schema.json",
}


def load_rules() -> dict:
    doc = json.loads(RULES_PATH.read_text(encoding="utf-8"))
    assert doc.get("schema_version") == "1.1", doc
    by = doc["by_task_type"]
    assert set(by) == {
        "historical_replay",
        "remote_detection",
        "single_remote_detection",
    }, by
    return by


def forbidden_not_schema(forbidden: list[str]) -> dict | None:
    if not forbidden:
        return None
    if len(forbidden) == 1:
        return {"required": [forbidden[0]]}
    return {
        "anyOf": [{"required": [name]} for name in forbidden],
    }


def build_if_then(task_type: str, required: list[str], forbidden: list[str]) -> dict:
    params: dict = {
        "type": "object",
        "required": list(required),
    }
    # Attach $ref shapes for required object fields (aligns with structural schemas).
    props = {}
    for name in required:
        if name in FIELD_SCHEMA_REF:
            props[name] = {"$ref": FIELD_SCHEMA_REF[name]}
        elif name == "execute_ip":
            props[name] = {"type": "string", "minLength": 1}
    if props:
        params["properties"] = props
    not_schema = forbidden_not_schema(forbidden)
    if not_schema is not None:
        params["not"] = not_schema
    return {
        "if": {
            "properties": {"task_type": {"const": task_type}},
            "required": ["task_type"],
        },
        "then": {"properties": {"params": params}},
    }


def generate_schema(by: dict) -> dict:
    # Stable order matching historical envelope allOf (RD, SRD, HR).
    order = [
        "remote_detection",
        "single_remote_detection",
        "historical_replay",
    ]
    all_of = []
    for task_type in order:
        entry = by[task_type]
        all_of.append(
            build_if_then(task_type, entry["required"], entry["forbidden"])
        )
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://mission-planer.local/schemas/common/mission_params_by_task_type.1.1.generated.schema.json",
        "title": "MissionParamsByTaskType11Generated",
        "description": "GENERATED from mission_params_rules.1.1.json — do not edit by hand. "
        "Referenced by task_envelope.1.1.schema.json mission_submit allOf.",
        "allOf": all_of,
    }


def cpp_string_list(name: str, items: list[str]) -> str | None:
    if not items:
        return None
    body = ", ".join(f'"{x}"sv' for x in items)
    return f"inline constexpr std::string_view {name}[] = {{{body}}};"


def generate_hpp_clean(by: dict) -> str:
    parts = [
        "// GENERATED by scripts/generate_mission_params_rules.py — do not edit.",
        "// SSOT: schemas/common/mission_params_rules.1.1.json",
        "#pragma once",
        "",
        "#include <cstddef>",
        "#include <string_view>",
        "",
        "namespace satellite {",
        "namespace mission_params_rules {",
        "",
        "using std::string_view_literals::operator\"\"sv;",
        "",
        "struct Rules {",
        "    const std::string_view* required;",
        "    std::size_t required_count;",
        "    const std::string_view* forbidden;",
        "    std::size_t forbidden_count;",
        "};",
        "",
    ]
    for task_type, entry in sorted(by.items()):
        ident = task_type.upper()
        req_line = cpp_string_list(f"kRequired_{ident}", entry["required"])
        forb_line = cpp_string_list(f"kForbidden_{ident}", entry["forbidden"])
        if req_line:
            parts.append(req_line)
        if forb_line:
            parts.append(forb_line)
        parts.append("")
    parts.append("inline const Rules* find(std::string_view task_type) {")
    for task_type, entry in sorted(by.items()):
        ident = task_type.upper()
        n_req = len(entry["required"])
        n_forb = len(entry["forbidden"])
        req_ptr = f"kRequired_{ident}" if n_req else "nullptr"
        forb_ptr = f"kForbidden_{ident}" if n_forb else "nullptr"
        parts.append(f'    if (task_type == "{task_type}"sv) {{')
        parts.append("        static const Rules r{")
        parts.append(f"            {req_ptr}, {n_req}, {forb_ptr}, {n_forb}}};")
        parts.append("        return &r;")
        parts.append("    }")
    parts.extend(
        [
            "    return nullptr;",
            "}",
            "",
            "}  // namespace mission_params_rules",
            "}  // namespace satellite",
            "",
        ]
    )
    return "\n".join(parts)


def write_or_check(path: Path, content: str, check: bool) -> bool:
    if check:
        if not path.exists():
            print(f"MISSING {path}", file=sys.stderr)
            return False
        existing = path.read_text(encoding="utf-8")
        if existing != content:
            print(f"STALE {path}", file=sys.stderr)
            return False
        print(f"OK {path.relative_to(ROOT)}")
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"WROTE {path.relative_to(ROOT)}")
    return True


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--check",
        action="store_true",
        help="verify generated files match rules (no write)",
    )
    args = ap.parse_args()
    by = load_rules()
    schema = generate_schema(by)
    schema_text = json.dumps(schema, indent=2, ensure_ascii=False) + "\n"
    hpp_text = generate_hpp_clean(by)
    ok = True
    ok &= write_or_check(SCHEMA_OUT, schema_text, args.check)
    ok &= write_or_check(HPP_OUT, hpp_text, args.check)
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
